Files tree view
fcsonline/react-transmission pull request #29
Opened 2017-02-11 12:14 UTC by edulan

Implement tree view in files tab

![screenshot from 2017-02-11 13 13 04](https://cloud.githubusercontent.com/assets/62171/22853622/e4f57d6e-f05b-11e6-8861-0377e187536f.png)

2017-02-11 16:15 UTC, fcsonline requested changes

2017-02-11 16:15 UTC, fcsonline commented on src/components/Inspector/Files/FileRow.js
> +        <PriorityButton />
We are missing something here. Those priority buttons should remember your decision, so they should read some property from entries.

2017-02-13 14:52 UTC, edulan commented on src/components/Inspector/Files/FileRow.js
> +        <PriorityButton />
Still WIP. Need to merge both `files` and `fileStats` on torrent to be able to consume priority info

2017-02-13 15:37 UTC, fcsonline commented on src/components/Inspector/Files/FileRow.js
> +        <PriorityButton />
ok!

2017-03-08 21:58 UTC, merged